steps:
- id: 'python hello world tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=python
    app="hello-world"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-'] # start immediately

- id: 'python guestbook tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=python
    app="guestbook"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-'] # start immediately

- id: 'java hello world tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=java
    app="hello-world"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-'] # start immediately
  
- id: 'java guestbook tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=java
    app="guestbook"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-'] # start immediately

- id: 'dotnet hello world tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=dotnet
    app="hello-world"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-'] # start immediately

# WARNING: guestbook test coverage is currently temporarily disabled
# - id: 'dotnet guestbook tests'
#   name: 'gcr.io/cloud-builders/gcloud'
#   entrypoint: 'bash'
#   args:
#   - '-c'
#   - |
#     lang=dotnet
#     app="guestbook"
#    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
#  waitFor: ['-'] # start immediately

- id: 'go hello world tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=go
    dir=golang
    app="hello-world"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${dir},_LANG=${lang},_APP=${app}
  waitFor: ['-']

- id: 'go guestbook tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=go
    dir=golang
    app="guestbook"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${dir},_LANG=${lang},_APP=${app}
  waitFor: ['-']

- id: 'nodejs hello world tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=nodejs
    app="hello-world"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-']

- id: 'nodejs guestbook tests'
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    lang=nodejs
    app="guestbook"
    gcloud builds submit . --config cloudbuild.tmpl.yaml --substitutions _DIR=${lang},_LANG=${lang},_APP=${app}
  waitFor: ['-']
timeout: 2500s

